### ISSUE TITLE
Using a custom pre component for code blocks

### ISSUE THREAD

**Issue by eburghar** [pngwn/MDsveX#437] opened 2022-03-11 15:52 UTC
Hi,

I wanted to use a custom `pre` components to achieve a lightbox effect on code blocks when you click inside. You can see the effect in [this post](https://itsufficient.me/blog/newblog) by clicking on any code block.

I had for that to change the source code by replacing `pre` by `Components.pre`, but I think mdsvex could easily detect if the `pre` has been overridden and prefix element by `Components.` if necessary. It would be consistent with what happens in other part of the code.

`packages/mdsvex/src/transformers/index.ts`

```javascript
		return `<Components.pre class="language-${normalised_lang}">{@html \`<code class="language-${normalised_lang}">${highlighted}</code>\`}</Components.pre>`;
	} else {
		const highlighted = escape_svelty(escape(code));
		return `<Components.pre class="language-${normalised_lang}">{@html \`<code class="language-${normalised_lang}">${highlighted}</code>\`}</Components.pre>`;
	}
```

I just don't see clearly how to access `components` inside `code_lighlight()` so I couln't send a PR.

Regards

**Comment by pngwn** [comment] 2022-03-27 11:49
Duplicate of #100

**Closed by pngwn** 2022-03-27 11:49 UTC
