### ISSUE TITLE
escaped html characters are parsed as actual html

### ISSUE THREAD

**Issue by tcoopman** [pngwn/MDsveX#301] opened 2021-09-07 13:49 UTC
Trying to parse:

```markdown
A paragraph started with &lt;h2&gt; 
```

results in: `</p> attempted to close <p> that was already automatically closed by <h2>`

Putting the escaped html chars between backticks renders them correctly, but I don't see why this should be necessary.

**Comment by pngwn** [comment] 2021-09-07 23:19
I'd need to look a bit more closely into this but I've seen issues in the past with remark or rehype automatically decoding entities which would cause this problem.

**Comment by pngwn** [comment] 2021-09-10 15:12
Duplicate of #296.

**Closed by pngwn** 2021-09-10 15:12 UTC
Labels: bug, markdown, v1
