### ISSUE TITLE
Add feature to export all frontmatter as `stuff` within SvelteKit

### ISSUE THREAD

**Issue by didier** [pngwn/MDsveX#448] opened 2022-05-08 14:18 UTC
Would be awesome if we could implement a feature like this. I much prefer working with (named) layouts in SvelteKit over MDsveX layouts.

**Comment by furudean** [comment] 2022-05-27 15:42
Duplicate of #313? It looks like what's suggested in your post will end up being the solution anyway.

**Closed** 2022-05-27 16:31 UTC
Labels: hmmm, mdsvex
