### ISSUE TITLE
Syntax highlighter for IDE

### ISSUE THREAD

**Issue by ghostdevv** [pngwn/MDsveX#297] opened 2021-08-29 21:01 UTC
I love writing my sites in markdown but it's a pain in the ass, there is no mdsvex extension from what I can see, and it's such a pain to write svelte logic inside of svx/md file

Any advice/something I missed?

**Comment by pngwn** [comment] 2021-08-30 14:38
Nothing at the minute but I have plans for this in the future. Duplicate of #121

**Closed by pngwn** 2021-08-30 14:38 UTC
