### ISSUE TITLE
Whitespaces removed with custom highlight function

### ISSUE THREAD

**Issue by alexanderniebuhr** [pngwn/MDsveX#318] opened 2021-10-12 08:29 UTC
I am setting up a new project with MDsevX and custom shiki highlight. I also saw this issue mentioned in some other issue, but never found an answer to it.

This is an example code block in my `.svx` file
![image](https://user-images.githubusercontent.com/45965090/136920424-e05955bf-2a4b-48af-bd46-29aee22674e4.png)

I am using following custom highlight function
```
async function highlighter(code, lang = 'text', metastring) {
  const shiki = await getHighlighter({
    theme: 'poimandres',
  })
  return escapeSvelte(shiki.codeToHtml(code, lang))
}
```
The result looks like
![image](https://user-images.githubusercontent.com/45965090/136920553-c5e355f8-3d94-4bff-b5da-cc738b6229f3.png)

**Comment by jthegedus** [comment] 2021-10-13 21:55
this is a duplicate of #212

**Closed as completed** 2021-10-14 05:38 UTC
